const SET_MATRIX = 'SET_MATRIX';
const SET_INCREMENT = 'SET_INCREMENT';
const SET_NUMBER_TO_CUT = 'SET_NUMBER_TO_CUT';
const SET_CLOSEST_VALUES = 'SET_CLOSEST_VALUES';
const SET_CLEAR_VALUES = 'SET_CLEAR_VALUES';
const SET_ROW_PERCENTAGE = 'SET_ROW_PERCENTAGE';
const SET_CLEAR_DEPOSIT = 'SET_CLEAR_DEPOSIT';
const SET_NEW_ROW = 'SET_NEW_ROW';
const SET_NEW_ROW_DATA = 'SET_NEW_ROW_DATA';
const SET_DELETE_ROW = 'SET_DELETE_ROW';

export {
  SET_MATRIX,
  SET_INCREMENT,
  SET_NUMBER_TO_CUT,
  SET_CLOSEST_VALUES,
  SET_CLEAR_VALUES,
  SET_ROW_PERCENTAGE,
  SET_CLEAR_DEPOSIT,
  SET_NEW_ROW,
  SET_NEW_ROW_DATA,
  SET_DELETE_ROW,
};
